### ISSUE TITLE
trezor: check wether passphrase is correct after user enters it

### ISSUE THREAD

**Issue by molecular** [mycelium-com/wallet#169]
see #168 for how this can mislead users (like me)

**Comment by molecular** [comment]
In case this doesn't make it into the next realease, alternatively you could change the message "Transaction rejected by network, maybe wallet isn't synced" to "Transaction rejected by network, maybe wallet isn't synced or if this is a trezor wallet, maybe you entered the wrong passphrase".

**Comment by Giszmo** [comment]
old issue. @DanielWeigl is it fixed?

**Comment by molecular** [comment]
this is fixed. The user is informed "wallet doesn't match passphrase".

**Comment by molecular** [comment]
sorry, I though this was electrum. Not sure if this is fixed... will check...

**Comment by Giszmo** [comment]
It is not fixed. Damn, I spent an hour with a flaky usb cable on a bus, remembering the wrong passphrase.

keepkey here

**Comment by Giszmo** [comment]
Will be fixed in the next release.

**Comment by Giszmo** [comment]
Error message is "Probably wrong passphrase" since a long time.
